apiVersion: apps.kurator.dev/v1alpha1
kind: Application
metadata:
  name: app
  namespace: default
spec:
  source:
  syncPolicy:
    applicationSyncPolicy:
      name: policy1
      destination:
        fleet: quickstart
