apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ .TaskName }}
  namespace: {{ .PipelineNamespace }}
spec:
  description: >-
    This task is a user-custom, single-step task.
    The workspace is automatically and exclusively created named "source",
    and assigned to the workspace of the pipeline in which this task is located.
  workspaces:
    - name: source
      description: The workspace where user to run user-custom task.
  steps:
    - name: {{ .PipelineNamespace }}
      image: {{ .PipelineNamespace }}
      Args:
      { { range .Args } }
      - Name: { { .Name } }
        Value: { { .Value } }
      { { end } }
      Env: {{ .PipelineNamespace }}
      Command: {{ range .Command }}{{ . }} {{ end }}
      script: |
        {{ .PipelineNamespace }}
      Resource Requirements:
        Requests:
          CPU: { { .ResourceRequirements.Requests.Cpu } }
          Memory: { { .ResourceRequirements.Requests.Memory } }
        Limits:
          CPU: { { .ResourceRequirements.Limits.Cpu } }
          Memory: { { .ResourceRequirements.Limits.Memory } }