apiVersion: backup.kurator.dev/v1alpha1
kind: Backup
metadata:
  name: select-labels
  namespace: default
spec:
  destination:
    fleet: quickstart
  policy:
    resourceFilter:
      labelSelector:
        matchLabels:
          app: busybox
    ttl: 720h  # 30 * 24 hours
