apiVersion: v1
kind: Namespace
metadata:
  name: kurator-backup
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: kurator-backup
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "echo Hello Kurator!  && sleep 3600"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kurator-host-control-plane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: kurator-backup
spec:
  storageClassName: ""  # using current pv setting, rather than dynamic pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-with-pv
  namespace: kurator-backup
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "echo Hello Kurator!! > /test-pvc/hello.txt && sleep 3600"]
      volumeMounts:
        - name: test-volume
          mountPath: /test-pvc
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc
