apiVersion: v1
kind: ServiceAccount
metadata:
  name: kurator-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kurator-pipeline-binding
subjects:
  - kind: ServiceAccount
    name: kurator-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kurator-pipeline
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kurator-pipeline
  namespace: kurator-pipeline
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
      - delete
