apiVersion: apps.kurator.dev/v1alpha1
kind: Application
metadata:
  name: app-helmrepo
  namespace: default
spec:
  source:
    helmRepo:
      interval: 5m
      url: https://stefanprodan.github.io/podinfo
  syncPolicy:
    - destination:
        fleet: fleet-helmrepo1
      helm:
        releaseName: podinfo
        chart:
          spec:
            chart: podinfo
        interval: 50m
        install:
          remediation:
            retries: 3
        values:
          redis:
            enabled: true
            repository: public.ecr.aws/docker/library/redis
            tag: 7.0.6
          ingress:
            enabled: true
            className: nginx
    - destination:
        fleet: fleet-helmrepo2
      helm:
        releaseName: podinfo
        chart:
          spec:
            chart: podinfo
        interval: 50m
        install:
          remediation:
            retries: 3
        values:
          redis:
            enabled: true
            repository: public.ecr.aws/docker/library/redis
            tag: 7.0.6
          ingress:
            enabled: true
            className: nginx
