apiVersion: pipeline.kurator.dev/v1alpha1
kind: Pipeline
metadata:
  name: quick-start
  namespace: kurator-pipeline
spec:
  description: "this is a quick-start pipeline, it shows how to use customTask and predefined Task in a pipeline"
  tasks:
    - name: git-clone
      predefinedTask:
        name: git-clone
        params:
          git-secret-name: git-credentials
    - name: cat-readme
      customTask:
        image: zshusers/zsh:4.3.15
        command:
          - /bin/sh
          - -c
        args:
          - "cat $(workspaces.source.path)/README.md"
    - name: go-test
      predefinedTask:
        name: go-test
        params:
          packages: ./...
    - name: go-lint
      predefinedTask:
        name: go-lint
        params:
          packages: "./..."
          flags: "--disable=errcheck,unused,gosimple,staticcheck --verbose --timeout 10m"
    - name: build-and-push-image
      predefinedTask:
        name: build-and-push-image
        params:
          image-name: "ghcr.io/xieql/kurator-final:0.4.1"
          extra-args: "--skip-tls-verify"
