apiVersion: v1
kind: Namespace
metadata:
  name: kurator-backup
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: kurator-backup
  labels:
    app: busybox
spec:
  automountServiceAccountToken: false
  hostIPC: true
  containers:
    - name: busybox
      image: busybox:1.35
      args:
        - sleep
        - 1d
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-with-pv
  namespace: kurator-backup
  labels:
    app: busybox-with-pv
spec:
  automountServiceAccountToken: false
  hostIPC: true
  volumes:
    - name: kurator-backup-storage
      persistentVolumeClaim:
        claimName: kurator-backup-claim
  containers:
    - name: busybox
      image: busybox:1.35
      args:
        - sleep
        - 1d
      volumeMounts:
        - mountPath: "/kurator-test"
          name: kurator-backup-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kurator-backup-claim
  namespace: kurator-backup
  labels:
    app: busybox-with-pv
spec:
  storageClassName: kurator-backup-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kurator-backup-volume
  labels:
    app: busybox-with-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: kurator-backup-local
  persistentVolumeReclaimPolicy: Delete
  local:
    path: "/tmp"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kurator-backup-local
  labels:
    app: busybox-with-pv
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
