apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: kurator-pipeline-triggertemplate
  namespace: kurator-pipeline
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourceTemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: kurator-pipeline-pipeline-run-
        namespace: $(tt.params.namespace)
      spec:
        serviceAccountName: tekton-triggers-example-sa
        pipelineRef:
          name: kurator-pipeline-pipeline
        params:
          - name: git-revision
            value: $(tt.params.gitrevision)
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: url
            value: registry.kube-system.svc.cluster.local/my-image # docker-repo-location.com/repo:kurator-pipeline
        workspaces:
          - name: git-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: kurator-pipeline-pipelinebinding
  namespace: kurator-pipeline
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: kurator-pipeline
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: kurator-pipeline-listener
  namespace: kurator-pipeline
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - bindings:
        - ref: kurator-pipeline-pipelinebinding
      template:
        ref: kurator-pipeline-triggertemplate